### ISSUE TITLE
adj_list_serialize_bug_fix.hpp not found error

### ISSUE THREAD

**Issue by JonathanGallagher** [esa/pagmo#92]
I cloned, built and installed the newest version of PyGMO/PaGMO from github on opensuse 13.2.   I then tried to compile a test project (that works on an older version, on ubuntu).  The error I get is:

    /usr/local/include/pagmo/src/serialization.h:28:42: 
    fatal error: adj_list_serialize_bug_fix.hpp: No such
    file or directory
    #include "adj_list_serialize_bug_fix.hpp"

I then checked "/usr/local/include/pagmo/src" and indeed the file was not present.  I then tried with a fresh clone and build of PaGMO, and the error persisted.  I then did the silliest thing I could think to do, and manuallly copied the file that was being searched for into the include directory.  Now the build succeeded, but the executable does not work.

Here is the error I get when trying to build and run:

    ./main_single
    terminate called after throwing an instance of
    boost::exception_detail::clone_impl
      <boost::exception_detail::error_info_injector<std::length_error> >'
    what():  circular_buffer

Any clue what is going on here?  For completeness here is the project I am trying to build.

    https://github.com/JGallagAtESG/PaGMO-Stub

It is not a real problem, just a test that the build environment works, and that the pagmo libraries are being correctly linked against, etc; it worked a two months ago on Ubuntu 14.04.

**Comment by darioizzo** [comment]
Jhonatan,

Missing header is fixed by commit 802e32877cec4c983d5b7c28cdfbef2de5525606.

The second error is probably due to the fact that you are linking to the external pagmo library. In which case you need to compile using the flags: -std=c++11 -pthread -DNDEBUG -lpagmo

In this case, -DNDEBUG is particularly important as without boost circular_buffer will throw the exception whenever a pagmo problem is used.

**Comment by JPelamatti** [comment]
Hello,
I am also having the exact same issue as Jonathan with the circular_buffer, but unfortunately adding the  -std=c++11 -pthread -DNDEBUG and -lpagmo flags to the compiler.cmake of my application did not solve it.  Am I also supposed to modify the compile flags of other parts of the library or linked libraries such as Boost?

Thanks in advance for the help
